name: Android CI
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'temurin'
          java-version: 18 
      - name: Build with Gradle
        run: ./gradlew build
      - name: UpLoad Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
        
        
        
    
    
    
  



